version: 3

tasks:
  preBuild:
    cmds:
      - go mod download
      - go mod tidy

  build:
    desc: Build
    deps: [ preBuild ]
    cmds:
      - go build ./...

  dependencyUpdates:
    desc: Show dependency updates
    cmds:
      - go list -u -m -json all | go-mod-outdated -update -direct

  lint:
    desc: Lint
    cmds:
      - golangci-lint run

  mingo:
    cmds:
      - mise exec go@1.23.5 -- mise install 'go:github.com/bobg/mingo/cmd/mingo@0.12.0'
      - mise exec 'go:github.com/bobg/mingo/cmd/mingo@0.12.0' -- mingo -tests
